
WITH_DOMAIN(NoDomain)
WITH_DOMAIN(GameEngine)
WITH_DOMAIN(Sound)
WITH_DOMAIN(Video)
WITH_DOMAIN(Video_Light)
WITH_DOMAIN(MD2)
WITH_DOMAIN(GUI)
WITH_DOMAIN(IA)
WITH_DOMAIN(Map)
WITH_DOMAIN(Game)

#ifdef COMPILE_TOOLS
WITH_DOMAIN(Tools)
#endif
